# Generated by Django 4.1.6 on 2023-03-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avator",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
