# Generated by Django 4.1.6 on 2023-03-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avator",
            field=models.URLField(blank=True),
        ),
    ]
