# Generated by Django 4.1.6 on 2023-03-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="namw",
            new_name="name",
        ),
    ]
